<template>
  <div class="icon-wrapper" :class="icon_size" @click="$emit('click')">
    <svg
      v-if="name === 'quiz'"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      version="1.1"
    >
      <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
      <g>
        <g>
          <g>
            <g>
              <g transform="translate(3 3)">
                <g>
                  <path
                    d="M4.5-.75H1.5C.257359-.75-.75.257359-.75 1.5V4.5L-.742288 4.68007C-.629877 5.86545.337877 6.75 1.5 6.75H4.5C5.74264 6.75 6.75 5.74264 6.75 4.5V1.5C6.75.257359 5.74264-.75 4.5-.75ZM1.5.75H4.5C4.91421.75 5.25 1.08579 5.25 1.5V4.5C5.25 4.91421 4.91421 5.25 4.5 5.25H1.5C1.11282 5.25.789946 4.95488.753466 4.57312L.749154 4.46439 .75 1.5C.75 1.08579 1.08579.75 1.5.75Z"
                    stroke="none"
                    :fill="color"
                  />
                  <path
                    d="M16.5-.75H10.5C9.25736-.75 8.25.257359 8.25 1.5V4.5L8.25771 4.68007C8.37012 5.86545 9.33788 6.75 10.5 6.75H16.5C17.7426 6.75 18.75 5.74264 18.75 4.5V1.5C18.75.257359 17.7426-.75 16.5-.75ZM10.5.75H16.5C16.9142.75 17.25 1.08579 17.25 1.5V4.5C17.25 4.91421 16.9142 5.25 16.5 5.25H10.5C10.1128 5.25 9.78995 4.95488 9.75347 4.57312L9.74915 4.46439 9.75 1.5C9.75 1.08579 10.0858.75 10.5.75Z"
                    stroke="none"
                    :fill="color"
                  />
                  <path
                    d="M8.04634 9.96406C8.34233 9.6743 8.81718 9.67935 9.10694 9.97534 9.37036 10.2444 9.39013 10.6613 9.16917 10.9526L9.09566 11.0359 4.77366 15.2669C4.50646 15.5285 4.09307 15.5501 3.80176 15.3332L3.7183 15.261 2.2993 13.84C2.00661 13.5469 2.00694 13.072 2.30004 12.7793 2.5665 12.5132 2.98318 12.4893 3.27664 12.7074L3.3607 12.78 4.254 13.676 8.04634 9.96406Z"
                    stroke="none"
                    :fill="color"
                  />
                  <path
                    d="M5.357 8.679C5.77121 8.679 6.107 9.01479 6.107 9.429 6.107 9.8087 5.82485 10.1225 5.45877 10.1722L5.357 10.179H2.49C1.57707 10.179.828357 10.8821.755768 11.7763L.75 11.919V15.51C.75 16.4229 1.45307 17.1716 2.34729 17.2442L2.49 17.25H6.081C6.99393 17.25 7.74264 16.5469 7.81523 15.6527L7.821 15.51V14.786C7.821 14.3718 8.15679 14.036 8.571 14.036 8.9507 14.036 9.26449 14.3182 9.31415 14.6842L9.321 14.786V15.51C9.321 17.2377 7.96872 18.6496 6.26486 18.7449L6.081 18.75H2.49C.7623 18.75-.649556 17.3977-.744871 15.6939L-.75 15.51V11.919C-.75 10.1913.60228 8.77944 2.30614 8.68413L2.49 8.679H5.357Z"
                    stroke="none"
                    :fill="color"
                  />
                  <path
                    d="M16.5 8.25H13.5C12.2574 8.25 11.25 9.25736 11.25 10.5V13.5L11.2577 13.6801C11.3701 14.8654 12.3379 15.75 13.5 15.75H16.5C17.7426 15.75 18.75 14.7426 18.75 13.5V10.5C18.75 9.25736 17.7426 8.25 16.5 8.25ZM13.5 9.75H16.5C16.9142 9.75 17.25 10.0858 17.25 10.5V13.5C17.25 13.9142 16.9142 14.25 16.5 14.25H13.5C13.1128 14.25 12.7899 13.9549 12.7535 13.5731L12.7492 13.4644 12.75 10.5C12.75 10.0858 13.0858 9.75 13.5 9.75Z"
                    stroke="none"
                    :fill="color"
                  />
                </g>
              </g>
              <rect
                fill-rule="evenodd"
                stroke="none"
                width="24"
                height="24"
                fill="none"
              />
            </g>
          </g>
        </g>
      </g>
    </svg>

    <svg
      v-if="name === 'services'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clip-path="url(#clip0_1722_31197)">
        <path
          d="M18.5 3H16C14.6193 3 13.5 4.11929 13.5 5.5V8C13.5 9.38071 14.6193 10.5 16 10.5H18.5C19.8807 10.5 21 9.38071 21 8V5.5C21 4.11929 19.8807 3 18.5 3Z"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M8 3H5.5C4.11929 3 3 4.11929 3 5.5V8C3 9.38071 4.11929 10.5 5.5 10.5H8C9.38071 10.5 10.5 9.38071 10.5 8V5.5C10.5 4.11929 9.38071 3 8 3Z"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M8 13.5H5.5C4.11929 13.5 3 14.6193 3 16V18.5C3 19.8807 4.11929 21 5.5 21H8C9.38071 21 10.5 19.8807 10.5 18.5V16C10.5 14.6193 9.38071 13.5 8 13.5Z"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M17.25 21C16.2554 21 15.3016 20.6049 14.5983 19.9017C13.8951 19.1984 13.5 18.2446 13.5 17.25C13.5 16.2554 13.8951 15.3016 14.5983 14.5983C15.3016 13.8951 16.2554 13.5 17.25 13.5C18.2446 13.5 19.1984 13.8951 19.9017 14.5983C20.6049 15.3016 21 16.2554 21 17.25C21 18.2446 20.6049 19.1984 19.9017 19.9017C19.1984 20.6049 18.2446 21 17.25 21Z"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_1722_31197">
          <rect width="24" height="24" fill="white" />
        </clipPath>
      </defs>
    </svg>

    <svg
      v-if="name === 'favorites'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clip-path="url(#clip0_5776_29000)">
        <path
          d="M13.555 15.856V15.856C13.1425 16.2683 12.5832 16.4999 12 16.5V16.5C11.4168 16.4999 10.8575 16.2683 10.445 15.856L7.80999 13.221V13.221C6.73 12.141 6.73 10.39 7.80999 9.31C8.88998 8.23001 10.641 8.23001 11.721 9.31L12 9.589L12.279 9.31V9.31C13.359 8.23001 15.11 8.23001 16.19 9.31C17.27 10.39 17.27 12.141 16.19 13.221L13.555 15.856Z"
          :stroke="color"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
          :stroke="color"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_5776_29000">
          <rect width="24" height="24" fill="white" />
        </clipPath>
      </defs>
    </svg>

    <svg
      v-if="name === 'results'"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
    >
      <path
        :fill="color"
        d="M14.5 2.25a2.25 2.25 0 0 1 2.245 2.096l.005.154V14a.75.75 0 0 1-1.493.102L15.25 14V4.5a.75.75 0 0 0-.648-.743L14.5 3.75h-11a.75.75 0 0 0-.743.648L2.75 4.5v15c0 .38.282.694.648.743l.102.007h11a.75.75 0 0 0 .743-.648l.007-.102v-.184a.75.75 0 0 1 1.493-.102l.007.102v.184a2.25 2.25 0 0 1-2.096 2.245l-.154.005h-11a2.25 2.25 0 0 1-2.245-2.096L1.25 19.5v-15a2.25 2.25 0 0 1 2.096-2.245L3.5 2.25h11Z"
      />
      <path
        :fill="color"
        d="M17.292 8.25c.499 0 .992.1 1.45.292l.227.104.654.327c.51.255.955.623 1.301 1.075l.142.199 1.558 2.337a.75.75 0 0 1-1.18.92l-.068-.088-1.558-2.337a2.25 2.25 0 0 0-.695-.67l-.171-.095-.654-.326a2.25 2.25 0 0 0-.797-.228l-.21-.01H16a.75.75 0 0 1-.102-1.493L16 8.25h1.292ZM12.551 10.25c.552.008 1.08.217 1.486.584l.131.127 2.38 2.521a.75.75 0 0 1 .144.81l-.052.099a.75.75 0 0 1-1.19.12l-.032-.04-2.34-2.48a.768.768 0 0 0-.425-.23l-.123-.01a.769.769 0 0 0-.71 1.088l.059.105 2.987 4.493c.36.543.874.963 1.474 1.208l.203.076 4.695 1.568a.75.75 0 0 1-.377 1.448l-.099-.026-4.694-1.567a4.75 4.75 0 0 1-2.3-1.66l-.151-.216-2.988-4.494a2.268 2.268 0 0 1 1.922-3.524Z"
      />
      <path
        :fill="color"
        d="M17.5 13.25a.75.75 0 0 1 .102 1.493l-.102.007H16a.75.75 0 0 1-.102-1.493L16 13.25h1.5ZM7 12.75a.75.75 0 0 1 .102 1.493L7 14.25H5a.75.75 0 0 1-.102-1.493L5 12.75h2ZM9 15.75a.75.75 0 0 1 .102 1.493L9 17.25H5a.75.75 0 0 1-.102-1.493L5 15.75h4ZM11.47 5.47a.75.75 0 0 1 1.133.976l-.073.084-3 3a.75.75 0 0 1-.767.182l-.098-.041-1.517-.759L5.53 10.53a.75.75 0 0 1-.976.073l-.084-.073a.75.75 0 0 1-.073-.976l.073-.084 2-2a.75.75 0 0 1 .767-.182l.098.041 1.516.758L11.47 5.47Z"
      />
      <path fill="none" d="M0 0h24v24H0z" />
    </svg>

    <svg
      v-if="name === 'download'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M12 3V17M12 17L9 14M12 17L15 14M8 10H5C3.895 10 3 10.895 3 12V19C3 20.105 3.895 21 5 21H19C20.105 21 21 20.105 21 19V12C21 10.895 20.105 10 19 10H16"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>

    <svg
      v-if="name === 'trash'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M18.5 6.5V19C18.5 19.5304 18.2893 20.0391 17.9142 20.4142C17.5391 20.7893 17.0304 21 16.5 21H7.5C6.96957 21 6.46086 20.7893 6.08579 20.4142C5.71071 20.0391 5.5 19.5304 5.5 19V6.5M9 17H15M9 13H15M8.5 6.5V4.5C8.5 4.10218 8.65804 3.72064 8.93934 3.43934C9.22064 3.15804 9.60218 3 10 3H14C14.3978 3 14.7794 3.15804 15.0607 3.43934C15.342 3.72064 15.5 4.10218 15.5 4.5V6.5M20 6.5H4"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>

    <svg
      v-if="name === 'close'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clip-path="url(#clip0_1555_25197)">
        <path
          d="M18 6.35645L6 18.3564M18 18.3564L6 6.35645"
          :stroke="color"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_1555_25197">
          <rect width="24" height="24" fill="white" />
        </clipPath>
      </defs>
    </svg>

    <svg
      v-if="name === 'document-file-clip'"
      width="48"
      height="48"
      viewBox="0 0 48 48"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clip-path="url(#clip0_1555_25026)">
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M38.2426 12.776L33.224 7.75736C32.0988 6.63215 30.5727 6.00001 28.9814 6H14C12.4087 6 10.8826 6.63214 9.75736 7.75736C8.63214 8.88258 8 10.4087 8 12V36C8 37.5913 8.63214 39.1174 9.75736 40.2426C10.8826 41.3679 12.4087 42 14 42H34C35.5913 42 37.1174 41.3679 38.2426 40.2426C39.3679 39.1174 40 37.5913 40 36V17.0186C40 15.4273 39.3679 13.9012 38.2426 12.776Z"
          :stroke="color"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M24 28V21C24 20.2044 24.3161 19.4413 24.8787 18.8787C25.4413 18.3161 26.2044 18 27 18C27.7956 18 28.5587 18.3161 29.1213 18.8787C29.6839 19.4413 30 20.2044 30 21V28C30 29.5913 29.3679 31.1174 28.2426 32.2426C27.1174 33.3679 25.5913 34 24 34C22.4087 34 20.8826 33.3679 19.7574 32.2426C18.6321 31.1174 18 29.5913 18 28V22"
          :stroke="color"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_1555_25026">
          <rect width="48" height="48" fill="white" />
        </clipPath>
      </defs>
    </svg>

    <svg 
      v-if="name === 'document-file-download'" 
      width="40" 
      height="40" 
      viewBox="0 0 40 40" 
      fill="none" 
      xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_6638_111698)">
        <path 
          d="M30.6897 10.69L25.9763 5.97667C25.3513 5.35167 24.503 5 23.6197 5H11.6663C9.82467 5 8.33301 6.49167 8.33301 8.33333V31.6667C8.33301 33.5083 9.82467 35 11.6663 35H28.333C30.1747 35 31.6663 33.5083 31.6663 31.6667V13.0467C31.6663 12.1633 31.3147 11.315 30.6897 10.69Z" 
          :stroke="color" 
          stroke-width="1.5" 
          stroke-linecap="round" 
          stroke-linejoin="round"/>
        <path d="M18.4829 28.3326L15.0996 24.9492" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M21.6667 25.1504L18.4834 28.3337" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M18.4834 28.334V18.334" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M31.6663 13.3333H24.9997C24.0797 13.3333 23.333 12.5867 23.333 11.6667V5" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
      <defs>
        <clipPath id="clip0_6638_111698">
          <rect width="40" height="40" fill="white"/>
        </clipPath>
      </defs>
    </svg>


    <svg
      v-if="name === 'eye'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M14.122 9.88C15.293 11.051 15.293 12.952 14.122 14.125C12.951 15.296 11.05 15.296 9.877 14.125C8.706 12.954 8.706 11.053 9.877 9.88C11.05 8.707 12.95 8.707 14.122 9.88Z"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M3 12C3 11.341 3.152 10.689 3.446 10.088C4.961 6.991 8.309 5 12 5C15.691 5 19.039 6.991 20.554 10.088C20.848 10.689 21 11.341 21 12C21 12.659 20.848 13.311 20.554 13.912C19.039 17.009 15.691 19 12 19C8.309 19 4.961 17.009 3.446 13.912C3.152 13.311 3 12.659 3 12Z"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>

    <svg
      v-if="name === 'question'"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M12.0001 12.7114L13.3277 11.9738C13.9902 11.6058 14.4011 10.9075 14.4011 10.1496C14.3226 8.88931 13.2418 7.92854 11.981 7.99834C10.8544 7.95158 9.85397 8.71313 9.59912 9.81151M21.0041 12C21.0041 16.9726 16.973 21.0037 12.0003 21.0037C7.0277 21.0037 2.99658 16.9726 2.99658 12C2.99658 7.02733 7.0277 2.99622 12.0003 2.99622C16.973 2.99622 21.0041 7.02733 21.0041 12Z"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M12.1002 15.9018C12.1002 15.957 12.0554 16.0018 12.0002 16.0017C11.9449 16.0017 11.9002 15.957 11.9002 15.9017C11.9001 15.8465 11.9449 15.8017 12.0001 15.8017C12.0267 15.8016 12.0522 15.8122 12.0709 15.831C12.0897 15.8498 12.1003 15.8752 12.1002 15.9018"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>

    <svg
      v-if="name === 'arrow_left'"
      width="36"
      height="36"
      viewBox="0 0 36 36"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M7.5 18L28.5 18M7.5 18L15 25.5015M7.5 18L15 10.4985"
        :stroke="color"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>

    <svg v-if="name === 'arrow_big_left'" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_6793_111685)">
      <path d="M16.495 21L7.5 11.973L16.5 3" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
      <defs>
      <clipPath id="clip0_6793_111685">
      <rect width="24" height="24" fill="white" transform="matrix(-1 0 0 -1 24 24)"/>
      </clipPath>
      </defs>
    </svg>

    <svg v-if="name === 'arrow_big_right'" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_6793_111683)">
      <path d="M7.505 3L16.5 12.027L7.5 21" :stroke="color" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
      <defs>
      <clipPath id="clip0_6793_111683">
      <rect width="24" height="24" fill="white"/>
      </clipPath>
      </defs>
    </svg>

    <svg 
      v-if="name === 'square_plus'"
      width="28" 
      height="28" 
      viewBox="0 0 28 28" 
      fill="none" 
      xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_7637_136940)">
        <path 
          d="M20.9993 3.79297H6.99935C5.22694 3.79297 3.79102 5.22889 3.79102 7.0013V21.0013C3.79102 22.7737 5.22694 24.2096 6.99935 24.2096H20.9993C22.7717 24.2096 24.2077 22.7737 24.2077 21.0013V7.0013C24.2077 5.22889 22.7717 3.79297 20.9993 3.79297ZM6.99935 5.54297H20.9993C21.8053 5.54297 22.4577 6.19538 22.4577 7.0013V21.0013C22.4577 21.8072 21.8053 22.4596 20.9993 22.4596H6.99935C6.19343 22.4596 5.54102 21.8072 5.54102 21.0013V7.0013C5.54102 6.19538 6.19343 5.54297 6.99935 5.54297Z" fill="white"/>
        <path 
          d="M14 8.45703C14.443 8.45703 14.8091 8.78621 14.8671 9.2133L14.875 9.33203V18.6654C14.875 19.1486 14.4832 19.5404 14 19.5404C13.557 19.5404 13.1909 19.2111 13.1329 18.7841L13.125 18.6654V9.33203C13.125 8.84879 13.5168 8.45703 14 8.45703Z" fill="white"/>
        <path 
          d="M18.6673 13.125C19.1506 13.125 19.5423 13.5168 19.5423 14C19.5423 14.443 19.2131 14.8091 18.7861 14.8671L18.6673 14.875H9.33398C8.85074 14.875 8.45898 14.4832 8.45898 14C8.45898 13.557 8.78816 13.1909 9.21525 13.1329L9.33398 13.125H18.6673Z" fill="white"/>
      </g>
      <defs>
      <clipPath id="clip0_7637_136940">
      <rect width="28" height="28" :fill="color"/>
      </clipPath>
      </defs>
    </svg>

    <svg 
      v-if="name === 'square_minus'"
      width="28" 
      height="28" 
      viewBox="0 0 28 28" 
      fill="none" 
      xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_7637_136939)">
      <path d="M20.9994 23.3346H6.99935C5.71018 23.3346 4.66602 22.2905 4.66602 21.0013V7.0013C4.66602 5.71214 5.71018 4.66797 6.99935 4.66797H20.9994C22.2885 4.66797 23.3327 5.71214 23.3327 7.0013V21.0013C23.3327 22.2905 22.2885 23.3346 20.9994 23.3346Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M18.6673 14H9.33398" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
      <defs>
      <clipPath id="clip0_7637_136939">
      <rect width="28" height="28" fill="white"/>
      </clipPath>
      </defs>
    </svg>

    <svg v-if="name === 'clip_attachment'" width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path 
        d="M6.90037 1.40395C8.10563 0.198685 10.0595 0.198685 11.2648 1.40395C12.4324 2.57155 12.4689 4.44173 11.3742 5.65324L11.2648 5.76837L6.44343 10.5897C5.6975 11.3356 4.48761 11.3356 3.74168 10.5897C3.02559 9.87363 2.99695 8.7299 3.65575 7.97963L3.74168 7.88797L7.39903 4.23061C7.5943 4.03535 7.91083 4.03535 8.1061 4.23061C8.28363 4.40812 8.29977 4.6859 8.1545 4.88164L8.1061 4.93772L4.44879 8.59503C4.09338 8.95043 4.09338 9.52723 4.44879 9.88263C4.7805 10.2143 5.30503 10.2364 5.66243 9.94897L5.73637 9.88263L10.5577 5.06128C11.3724 4.24654 11.3724 2.92579 10.5577 2.11105C9.7743 1.32765 8.52303 1.29752 7.70363 2.02066L7.60743 2.11105L2.78612 6.93236C1.51205 8.20643 1.51205 10.2712 2.78612 11.5453C4.02158 12.7808 6.0005 12.8182 7.28103 11.6576L7.39903 11.5453L10.325 8.6193C10.5203 8.42403 10.8368 8.42403 11.0321 8.6193C11.2096 8.79677 11.2258 9.07456 11.0805 9.2703L11.0321 9.32637L8.1061 12.2524C6.4415 13.917 3.74361 13.917 2.07901 12.2524C0.455019 10.6284 0.415406 8.02083 1.96019 6.3489L2.07901 6.2253L6.90037 1.40395Z" 
        :fill="color"/>
    </svg>

    <svg
      v-if="name === 'loud-storage-upload-2'" 
      width="121" height="121" viewBox="0 0 121 121" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g clip-path="url(#clip0_8231_10417)">
      <path d="M32.12 45.84C19.925 47.505 10.5 57.85 10.5 70.5C10.5 84.305 21.695 95.5 35.5 95.5H90.5C101.545 95.5 110.5 86.545 110.5 75.5C110.5 64.455 101.545 55.5 90.5 55.5C90.5 38.93 77.07 25.5 60.5 25.5C47.315 25.5 36.145 34.015 32.12 45.84Z" stroke="#9EA0B3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M49.665 63.835L60.5 53L71.335 63.835" stroke="#9EA0B3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M60.5 78V53" stroke="#9EA0B3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
      <defs>
      <clipPath id="clip0_8231_10417">
      <rect width="120" height="120" fill="white" transform="translate(0.5 0.5)"/>
      </clipPath>
      </defs>
    </svg>
  </div>
</template>

<script>
export default {
  props: {
    color: {
      type: String,
      required: false,
      default: 'currentColor'
    },
    name: {
      type: String,
      required: true
    },
    size: {
      type: String,
      default: 'sm'
    }
  },
  // 12 20 28 36 48
  data() {
    return {}
  },
  computed: {
    icon_size() {
      return this.size === 'fille' ? 'icon-full-size' : `icon-${this.size}`
    }
  }
}
</script>

<style lang="scss" scoped>
$sizes: (
  'xs': 12,
  'tn': 16,
  'sm': 24,
  'md': 32,
  'lg': 36,
  'xl': 48
);

@mixin icon-class($key, $value) {
  .icon-#{$key} {
    svg {
      width: #{$value}px;
      height: #{$value}px;
    }
  }
}

.icon-full-size {
  height: 100%;
  width: 100%;
}

@mixin generate-icon-sizes() {
  @each $key, $value in $sizes {
    @include icon-class($key, $value);
  }
}

@include generate-icon-sizes();
.icon-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-shrink: 0;
  flex-grow: 0;

  // svg {
  //   height: 48px;
  //   width: 48px;
  // }
}
</style>
